# Default values for kubed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
kubed:
  image: appscode/kubed
  pullPolicy: IfNotPresent
  tag: 0.2.0
## Install Default RBAC roles and bindings
rbac:
  ## If true, create & use RBAC resources
  create: false
  ## Ignored if rbac.create is true
  serviceAccountName: default
