snapshotter:
  Storage:
    gcs:
      bucket: restic
      prefix: minikube
    storageSecretName: snap-secret
  sanitize: true
  schedule: '@every 6h'
eventForwarder:
  eventNamespaces:
  - kube-system
  forwardWarningEvents: true
  notifyOnIngressAdd: true
  notifyOnStorageAdd: true
  receiver:
    notifier: mailgun
    to:
    - ops@example.com
janitors: {}
notifierSecretName: kubed-notifier
recycleBin:
  handle_update: false
  path: /tmp/kubed
  receiver:
    notifier: mailgun
    to:
    - ops@example.com
  ttl: 168h
