apiVersion: v1
data:
  config.yaml: c25hcHNob3R0ZXI6CiAgU3RvcmFnZToKICAgIHMzOgogICAgICBlbmRwb2ludDogJ3MzLmFtYXpvbmF3cy5jb20nCiAgICAgIGJ1Y2tldDoga3ViZWRiLXFhCiAgICAgIHByZWZpeDogbWluaWt1YmUKICAgIHN0b3JhZ2VTZWNyZXROYW1lOiBzbmFwLXNlY3JldAogIHNhbml0aXplOiB0cnVlCiAgc2NoZWR1bGU6ICdAZXZlcnkgNmgn
kind: Secret
metadata:
  creationTimestamp: 2017-07-26T05:32:09Z
  labels:
    app: kubed
  name: kubed-config
  namespace: kube-system
  resourceVersion: "5572"
  selfLink: /api/v1/namespaces/kube-system/secrets/kubed-config
  uid: c4dc8215-71c3-11e7-a5ec-0800273df5f2
type: Opaque
