kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: standard
