apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "name" . }}"
        release: "{{ .Release.Name }}"
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: {{ template "fullname" . }}
{{- end }}
      containers:
      - args:
        - run
        - --v=3
        image: '{{ .Values.kubed.image }}:{{ .Values.kubed.tag }}'
        imagePullPolicy: '{{ .Values.kubed.pullPolicy }}'
        name: kubed
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /tmp
            name: scratchdir
      volumes:
        - emptyDir: {}
          name: scratchdir
