apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubed.fullname" . }}
  labels:
    app: "{{ template "kubed.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: {{ `
clusterName: unicorn
enableConfigSyncer: true
` | trim | b64enc | quote }}
