{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubed.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubed.labels" . | nindent 4 }}
imagePullSecrets:
  {{- range $x := .Values.imagePullSecrets }}
  - name: "{{ $x }}"
  {{- end }}
{{ end }}
