apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubed.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubed.labels" . | nindent 4 }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: 8443
  selector:
    app: "{{ template "kubed.name" . }}"
    release: "{{ .Release.Name }}"
