apiVersion: v1
data:
  SMTP_FROM: eW91ci1zbXRwLWZyb20=
  SMTP_HOST: eW91ci1zbXRwLWhvc3Q=
  SMTP_INSECURE_SKIP_VERIFY: eW91ci1zbXRwLWluc2VjdXJlLXNraXAtdmVyaWZ5
  SMTP_PASSWORD: eW91ci1zbXRwLXBhc3N3b3Jk
  SMTP_PORT: eW91ci1zbXRwLXBvcnQ=
  SMTP_USERNAME: eW91ci1zbXRwLXVzZXJuYW1l
kind: Secret
metadata:
  creationTimestamp: 2017-07-25T01:57:17Z
  name: notifier-config
  namespace: kube-system
  resourceVersion: "2422"
  selfLink: /api/v1/namespaces/kube-system/secrets/notifier-config
  uid: 965cb1e8-70dc-11e7-9b0b-080027503732
type: Opaque
